### ISSUE TITLE
How to use it correctly?

### ISSUE THREAD

**Issue by clay001** [PeterZZQ/CellPath#1]

**Comment by clay001** [comment]
It is solved.

**Comment by PeterZZQ** [comment]
Hi it's the naming problem, the folder and the script inside it should be named `cellpath` instead of `CellPath`, I have updated the code, pls try clone and install again.

**Comment by clay001** [comment]
> Hi, it's the naming issue, the folder and the script inside it should be named `cellpath` instead of `CellPath`, I have updated the code, pls try clone and install again. Please fill feel to email me: [ziqi.zhang@gatech.edu](mailto:ziqi.zhang@gatech.edu) or post issue directly if you have any other problems w.r.t our package.

Yes, exactly, I found that, and also the init file should be change.
Thank you for your replying! I recently also digged into this topic, maybe we can discuss further when I read more.

**Comment by PeterZZQ** [comment]
> > Hi, it's the naming issue, the folder and the script inside it should be named `cellpath` instead of `CellPath`, I have updated the code, pls try clone and install again. Please fill feel to email me: [ziqi.zhang@gatech.edu](mailto:ziqi.zhang@gatech.edu) or post issue directly if you have any other problems w.r.t our package.
> 
> Yes, exactly, I found that, and also the init file should be changed.
> Thank you for your replying! I recently also digged into this topic, maybe we can discuss further when I read more.

Sure! No problem!
