### ISSUE TITLE
tweaks to README.md

### ISSUE THREAD

**Issue by jfass** [PeterZZQ/CellPath#2]
The dependencies listed include "sklearn >= 0.22.1" so I included sklearn in an attempted "conda create" to set up a virtual environment. There's no "sklearn" conda package, but there is "scikit-learn" ... which seems to work with the later "pip install" step.

Also, after cloning the repo, I needed to "cd CellPaths/" before running the "pip install ." command.

**Comment by PeterZZQ** [comment]
Hi,

Thanks for letting us know, have already updated the `README.md` file.
