### ISSUE TITLE
TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by ernohanninen** [PeterZZQ/CellPath#4]
Hello,

When running this code:

```
num_trajs = 4
flavor = "k-means"
num_metacells = 300

adata = anndata.read_h5ad("/media/ernohanninen/TOSHIBA/cycletree.h5ad")

cellpath_obj = cp.CellPath(adata = adata, preprocess = True)
cellpath_obj.all_in_one(flavor = flavor, num_metacells = num_metacells, n_neighs = 13, num_trajs = num_trajs, prop_insert = 0.0, seed = 0, mode = "exact")
```

I get the following error:

Traceback (most recent call last):
  File "run_CellPath.py", line 19, in <module>
    cellpath_obj.all_in_one(flavor = flavor, num_metacells = num_metacells, n_neighs = 13, num_trajs = num_trajs, prop_insert = 0.0, seed = 0, mode = "exact")
  File "/home/ernohanninen/miniconda3/envs/TRAenv/lib/python3.8/site-packages/cellpath/cellpath.py", line 349, in all_in_one
    self.meta_cell_construction(flavor = flavor, n_clusters = num_metacells, resolution = resolution, **kwargs)
  File "/home/ernohanninen/miniconda3/envs/TRAenv/lib/python3.8/site-packages/cellpath/cellpath.py", line 121, in meta_cell_construction
    self.X_clust, self.velo_clust = clust.meta_cells(self.adata, kernel = _kwargs["kernel"], 
  File "/home/ernohanninen/miniconda3/envs/TRAenv/lib/python3.8/site-packages/cellpath/clustering.py", line 136, in meta_cells
    k = KernelRidge(alpha, kernel, gamma)
TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given

**Comment by PeterZZQ** [comment]
Hi,

It was a bug due to the update of the sklearn package. I have updated the code on GitHub and also on Pypi. The bug should be fixed now. You can update your cellpath package with pip or directly pull the GitHub repo down to directly install from the source code.

**Comment by ernohanninen** [comment]
The code is running. Thank you!
