### ISSUE TITLE
Comparing trajectories between conditions

### ISSUE THREAD

**Issue by kousaa** [PeterZZQ/CellPath#5]
Hello CellPath team, 

thanks for building this tool, it has been great using it so far!

I was wondering if it is possible to identify which trajectories may change (either not happen at all, been depleted or reinforced) in different conditions of a dataset. An example would be differentiation trajectory at steady state and after treatment. Would there be a way to identify all trajectories in the combined dataset, and then pin point to the ones that are more prominent in the one or the other condition?  

Thanks a lot,
Anastasia

PS. I understand that this type of functionality may not be already present in your tool, but in the meantime it would be very helpful if I could color-code the cells within the de.de_plot function by condition. If you could provide some example code for this, that would be great!

**Comment by PeterZZQ** [comment]
Hi,

Yes, CellPath currently doesn't have the function to identify the trajectories that change across conditions. I think this could be an interesting problem to study. However, if you simply want to color-code the cells according to the condition in de_plot, I think you just need to do some small modifications to the original plotting code. In de_plot function, we use [this line](https://github.com/PeterZZQ/CellPath/blob/d4c4f3a08a1f6d29f7103a6371a6d03354db78c4/cellpath/de_analy.py#L204) to plot the cells. You can separate this line into two lines. In the first line, you plot cells under one condition, and in the second line you plot cells under another condition, you can assign different colors to differentiate the cells. It still requires that you have already known the alignment of trajectories across conditions.
